### PR TITLE
Fix so daysUntilClose keyword can be used under the pulls or issues keyword

### LINKED ISSUE #129: Using key 'daysUntilClose' with value 'false' under key 'pulls' still closes pull requests
I'm only want PR's to be marked as staled, and never closed. But issues should be marked staled and then closed. 
So I thought this configuration would work. But it seems that PR's are still closed, see example in PR https://github.com/johlju/DebugApps/pull/11.

Should this configuration work? 

```yml
limitPerRun: 30

pulls:
  daysUntilStale: 1
  daysUntilClose: false
  exemptProjects: true
  exemptMilestones: true
  staleLabel: abandoned
  exemptLabels:
    - needs review
    - on hold
    - waiting for CLA pass

  markComment: >
    Labeling this pull request (PR) as abandoned since it has gone 14 days or more
    since the last update. An abandoned PR can be continued by another contributor.
    The abandoned label will be removed if work on this PR is taken up again.

issues:
  daysUntilStale: 1
  daysUntilClose: 2
  exemptProjects: true
  exemptMilestones: true
  staleLabel: needs more information
  exemptLabels:
    - bug
    - enhancement
    - tests
    - documentation
    - resource proposal
    - on hold
    - new module submission
    - module proposal

  markComment: >
    This issue has been automatically marked as needs more information because
    it has not had activity from the community in the last 30 days. It will be
    closed if no further activity occurs within 10 days. If the issue is labelled
    with any of the work labels (e.g bug, enhancement, documentation, or tests)
    then the issue will not auto-close.

  closeComment: >
    This issue has been automatically closed because it is has not had activity
    from the community in the last 40 days.

```

### PR DESCRIPTION
**Pull request by johlju**
- Tests 
  - Added regression tests for daysUntilClose keyword when using pulls or issues keyword
  - Added regression tests for only keyword when using pulls or issues keyword
- Fix so daysUntilClose can be used under the pulls or issues keyword
- Fix so only can be used under the pulls or issues keyword

Fixes #129

### CODE REVIEW

File: lib/stale.js [hunk 1]
```diff
@@ -19,7 +19,8 @@ module.exports = class Stale {
   }
 
   async markAndSweep (type) {
-    const {only} = this.config
+    const only = this.getConfigValue(type, 'only')
```
Comment (bkeepers) [inline lib/stale.js]: Hmm, `getConfigValue` is meant for pulling values for specific types and falling back to the default. I don't think it should be needed here.

Comment (johlju) [reply lib/stale.js]: Done. I removed the last two commits, but kept two tests in a new commit.

**Comment by johlju** [comment]
Fixed a type in one of the tests descriptions. Ready to be reviewed again! Thanks!

**Comment by bkeepers** [comment]
Thanks @johlju !

This is deploying now and should be available for everyone soon.

**Comment by johlju** [comment]
Awesome! I updated the configuration in my test repo so I will see if it works by tomorrow.
