### PR TITLE
Make default comment friendlier and actionable (fixes #67)

### LINKED ISSUE #67: Add nuance to how stale works to encourage interaction from Maintainers in situations where contributors follow all the guidelines
👋 Wanted to memorialize a conversation that @gr2m @bkeepers @JasonEtco and I had with @keithamus at GitHub Universe this past week. Keith brought up a really valid point about first time contributors and the way a bot closing out their issue might affect future contributions to open source. **Everyone mentioned above, please feel free to edit my explanation as you see fit.**

Apologies for my paraphrasing: There are two types of issues that end up getting closed. There are issues where the submitter has done their best to reproduce and for one reason or another the issue doesn't get attention. The type is when the submitter is not responding or might not be following instructions. This type makes perfect sense for stale. It will close out issues that don't meet the bar for human interaction. 

However, the first type of issues where the submitter has done everything in their power to help describe the issue, there might be an opportunity to change the tone or interaction so that we could help empower new comers rather than have them get shut out by a bot. 

### Examples
I tried to pull up a few issues to try and describe these different circumstances. 

Here is a situation where a person opened an issue without filling out the proper documentation: https://github.com/atom/atom/issues/15889 This is a perfect candidate for stale or another bot to reply as rsese did in this instance. 

Here is a situation when the original opener of the issue `styurin` got an answer from a member of the project and never replied. In this case it seems that it's reasonable to close the issue b/c the original submitter never followed up: https://github.com/atom/atom/issues/12964

Here is a situation when the user took time to report an issue and someone added a label but there was no further interaction. I would imagine the issue got fixed at some point b/c the original submitter, `misaghshakeri`, never replied. https://github.com/atom/atom/issues/12548 However, I wonder if some sort of interaction or nuance could help provide context. 

### Possible Solutions
We could use the first-timer property returned from the GraphQL endpoint to change the behavior of the app. 

We could build a heuristic for how new a person is to GitHub to provide a nuanced response to stale.

We could be more opinionated/prescriptive on how we ask users to write their stale comment text. 
---

In short, I think stale is awesome. It's adoption and resulting data gives us a really cool opportunity to re-asses its interactions and further investigate the tone, context, and persona of stale that will best serve the needs of first time contributors up through maintainers.

### PR DESCRIPTION
**Pull request by waldyrious**
The default message posted by the bot is unnecessarily harsh and final-sounding, which has resulted in a lot of grief, summarized in #67.

Interestingly enough, even this repo decided against using the default message and has been using a friendlier and more constructive message for a while.

This change makes that message the default, so that other communities using this bot get a more positive experience out of the box.

### CODE REVIEW

**Comment by christianbundy** [comment]
@bkeepers Is there anything I can do to help move this forward? I'd love to see this merged.

**Comment by dwijnand** [comment]
I think this is just awaiting a review and a merge.

**Comment by dwijnand** [comment]
I think this is just awaiting a review and a merge.

**Comment by Download** [comment]
@bkeepers  This issue seems to need your attention...

Maybe you can invite some collaborators to help with reviewing and merging PRs?

**Comment by bkeepers** [comment]
I am no longer involved with the project. Maybe @tcbyrd or @JasonEtco could suggest someone that can help?

**Comment by Download** [comment]
@bkeepers Ok clear, thanks!
@JasonEtco Maybe invite some more collaborators to help with reviewing/merging?

File: lib/schema.js [hunk 1]
```diff
@@ -45,9 +45,8 @@ const schema = Joi.object().keys({
   exemptMilestones: fields.exemptMilestones.default(false),
   staleLabel: fields.staleLabel.default('wontfix'),
   markComment: fields.markComment.default(
-    'This issue has been automatically marked as stale because ' +
-    'it has not had recent activity. It will be closed if no further ' +
-    'activity occurs. Thank you for your contributions.'
+    'Is this still relevant? If so, what is blocking it? ' +
+    'Is there anything you can do to help move it forward?'
```
Comment (JasonEtco) [inline lib/schema.js]: This is a great change, but I'm worried that folks won't understand the repercussion of not commenting. This line feels important:

> It will be closed if no further activity occurs

Could you add that message back in somehow (not the specific wording, but that the issue will be closed if there's no more activity)?

**Comment by christianbundy** [comment]
Maybe we could just concat the two?

> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
>
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

**Comment by waldyrious** [comment]
Thanks @JasonEtco and @christianbundy for the suggestions. I re-added the note at the end, but removed the "Thank you for your contributions" because it sounds a little passive-aggressive to me coming after a "this issue will be closed" message. Let me know what you think. :)

**Comment by waldyrious** [comment]
Also, I wonder if moving the placement of "automatic" to the closure sentence may help with clarifying that no decision has been made yet:

> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
>
> This issue has been marked as stale because it has not had recent activity. It will be automatically closed if no further activity occurs.

WDYT?
